example: update existing project upload example
Sparkier/zeno_hub pull request #107
Opened 2023-08-25 00:37 UTC by cabreraalex

# Description

Creates a Jupyter Notebook to upload existing Zeno caches.

# Blocked by

- #99

2023-08-25 10:27 UTC, Sparkier requested changes

2023-08-25 10:27 UTC, Sparkier commented on backend/zeno_backend/database/select.py
> +
We currently always name it the same, so we don't really need this. I think it can always be named `data_id`.

2023-08-25 10:27 UTC, Sparkier commented on frontend/src/lib/components/instance-views/ListView.svelte
> +							: ''}
Don't think we need this.

2023-08-25 15:15 UTC, cabreraalex commented on backend/zeno_backend/server.py
> +    @api_app.post("/new-project", tags=["zeno"])
I think standard for REST api is to not put actions, so "new" describes the endpoint better and "post" describes the action I think?

2023-08-26 07:27 UTC, Sparkier approved these changes

2023-08-27 00:44 UTC, merged